# Generated by Django 2.2.6 on 2019-10-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='review',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
