# Generated by Django 2.2.6 on 2019-10-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipes_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='steep',
            field=models.FloatField(default=4),
            preserve_default=False,
        ),
    ]
