# Generated by Django 2.2.6 on 2019-10-22 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipecomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecomments',
            name='replay_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commentTo', to='recipe.RecipeComments'),
        ),
    ]
