# Generated by Django 2.2.6 on 2019-10-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20191023_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='nicotine_fluid',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipes',
            name='target_strength',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
