# Generated by Django 2.2.6 on 2019-10-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_recipes_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
