# Generated by Django 2.2.6 on 2019-10-25 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_auto_20191025_2019'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='juice',
            unique_together={('name', 'brand')},
        ),
    ]
