# Generated by Django 2.2.6 on 2019-10-25 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_auto_20191025_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='image_url',
        ),
    ]
